name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or your default branch like 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Install Railway CLI
        run: npm install -g railway

      - name: Login to Railway CLI
        run: railway login --apiKey ${{ secrets.RAILWAY_API_TOKEN }}

      - name: Deploy to Railway
        run: railway up --project ${{ secrets.RAILWAY_PROJECT_ID }} --environment ${{ secrets.RAILWAY_ENVIRONMENT_ID }}
